export const ActionTypes = {
    ADD_CUSTOMER_USER: 'ADD_CUSTOMER_USER',
    MULTIPLE_USERS: 'MULTIPLE_USERS',
    USER_ADD_FAILED: 'USER_ADD_FAILED',
    USER_LOGIN_SUCCESSFUL: 'USER_LOGIN_SUCCESSFUL',
    USER_LOGIN_FAILED_SUCCESSFUL : 'USER_LOGIN_FAILED_SUCCESSFUL',

    ADD_RESTAURANT: 'ADD_RESTAURANT',
    RES_MULTIPLE_USERS: 'RES_MULTIPLE_USERS',
    RES_ADD_FAILED: 'RES_ADD_FAILED',
    LOG_OUT : 'LOG_OUT',

    UPDATE_CART : 'UPDATE_CART',
    STORE_LOCATION : 'STORE_LOCATION'
}
  